FROM python:3.12-slim
WORKDIR /app
COPY ai_service/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY . /app
CMD ["uvicorn","ai_service.main:app","--host","0.0.0.0","--port","8001"]
